### ISSUE TITLE
Deliverable 2 Documents

### ISSUE THREAD

**Issue by Selliott452** [Selliott452/COS420#15]
# Documents for Deliverable 2

### Updates
- [ ] Update Project Description (if required).
- [ ] update User Story documents (if required).
- [ ] Update Product Backlog
- [ ] Update  Sprint Backlog
- [ ] Update the Team Member Report document.
- [ ] Update SRS document.
- [ ] Update Use Case Models and Descriptions document with potential new use cases.

### New Documents
- [ ] Sprint 2 review document
- [ ] Spring 3 review document
- [ ] Create Focus Group document
- [ ] Create Sequence Diagram document.
- [ ] Create the Domain Model document.
- [ ] Create the Architecture Design document with its description.
