### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by Selliott452** [Selliott452/COS420#16]
# Development
- [ ] Structure website
- [ ] Create basic schedule from dummy data
- [ ] Structure Database
- [ ] Create Account
- [ ] Store data associated with account

# Knowledge Acquisition
- [ ] Pick coding conventions
- [ ] Familiarize with React
- [ ] Familiarize with Firebase
- [ ] Familiarize with Express
- [ ] Familiarize with Node
